sudo: false
language: python
cache: pip

matrix:
    fast_finish: true
    include:
      - { python: "2.7", env: DJANGO_VERSION="1.8.*" }
      - { python: "2.7", env: DJANGO_VERSION="1.9.*" }
      - { python: "2.7", env: DJANGO_VERSION="1.10.*" }
      - { python: "2.7", env: DJANGO_VERSION="1.11.*" }

      - { python: "3.4", env: DJANGO_VERSION="1.11.*" }
      - { python: "3.4", env: DJANGO_VERSION="2.0.*" }

      - { python: "3.5", env: DJANGO_VERSION="1.11.*" }
      - { python: "3.5", env: DJANGO_VERSION="2.0.*" }
      - { python: "3.5", env: DJANGO_VERSION="2.1.*" }

      - { python: "3.6", env: DJANGO_VERSION="1.11.*" }
      - { python: "3.6", env: DJANGO_VERSION="2.0.*" }
      - { python: "3.6", env: DJANGO_VERSION="2.1.*" }

      - { python: "3.7", env: DJANGO_VERSION="2.0.*", dist: xenial, sudo: true }
      - { python: "3.7", env: DJANGO_VERSION="2.1.*", dist: xenial, sudo: true }

install:
    - pip install Django==${DJANGO_VERSION}
    - pip install codecov
    - pip install pytz

branches:
  only:
    - master

script:
  - coverage run --omit='setup.py' --source='.' runtests.py

after_success:
  - codecov
